### ISSUE TITLE
[1.7.10] TECHNO-Z Skin du joueur buggé

### ISSUE THREAD

**Issue by BLACKNIGHTXZ1** [BLACKNIGHTXZ1/Minecraft_Servers#5]
![image](https://user-images.githubusercontent.com/116629987/197800713-086cb0a0-719e-4598-8231-55bef2d7a236.png)

**Comment by BLACKNIGHTXZ1** [comment]
Réglé en ajoutant Skin Port

**Comment by quentin452** [comment]
solution trouvé en descativant smart moving
