### ISSUE TITLE
[1.7.10] TECHNO-Z Smart Moving ne fonctionne pas

### ISSUE THREAD

**Issue by quentin452** [BLACKNIGHTXZ1/Minecraft_Servers#6]

**Comment by quentin452** [comment]
incompat with vics modern warfare , skin port + smart moving and dependencies deleted

**Comment by BLACKNIGHTXZ1** [comment]
Non résolu

**Comment by BLACKNIGHTXZ1** [comment]
Aucune solution trouvée. VMW, Skin Port ne sont pas compatible avec Smart Moving.

**Comment by quentin452** [comment]
enfait smart moving est incompatible avec kin port , mais il est compatible avec VMW

**Comment by quentin452** [comment]
mais il est incompatible avec un autre mod , donc on le mettra pas dans le modpack

**Comment by quentin452** [comment]
incompat with foamfix mc18SkinSupport option

**Comment by quentin452** [comment]
duplicate of #5
